# Deploy to Firebase Hosting on merge (React 18)
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main   # change if your default branch is master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (LTS is safest, React 18 works fine on 18 or 20)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies (clean install from package-lock.json)
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Build React project
      - name: Build React App
        run: npm run build

      # 5️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONLINEEXAMTOO }}
          channelId: live
          projectId: onlineexamtoo
