name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # replace with your branch if not main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (ignore peer deps)
        run: npm install --legacy-peer-deps

      - name: Build React app
        run: npx react-scripts build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONLINEEXAMTOO }}
          channelId: live
          projectId: onlineexamtoo
