name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main   # change if your default branch is master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

